name: PlatformIO CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO
        run: |
          pip install --upgrade pip
          pip install platformio
          
      - name: Build firmware
        run: pio run
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: firmware-build
          path: .pio/build/*/firmware.bin
          retention-days: 30